### ISSUE TITLE
Create Google Chrome extensions plugin

### ISSUE THREAD

**Issue by 5ynax** [Asymmetric-InfoSec/Power-Response#111]
Create a plugin that collects all extension ID's and performs a validation of the plugin name for each.

**Comment by mikeclemson** [comment]
$extensionIDs = Get-Content 'C:\Apps\extensions.csv'

foreach ($extensionID in $extensionIDs) {
    $url = "https://chrome.google.com/webstore/detail/$extensionID"
    Try {
        $response = Invoke-WebRequest -Uri $url -UseBasicParsing
        $response.Content -match "<title>(?<title>.*)</title>" | Out-Null
        ($matches['title']) -replace " - Chrome Web Store",""
    } Catch {
        Write-Host "Extension $extensionID was not found"
    }
}

In my test against a system with Adware, all three extension IDs that were not found were associated with malware and had been pulled by Google.

**Comment by 5ynax** [comment]
implemented.
