### ISSUE TITLE
Hide Menu Items

### ISSUE THREAD

**Issue by valrkey** [Asymmetric-InfoSec/Power-Response#12]
Hide files/directories that aren't designed to be executed/navigated into when showing .

* Ignore all directories starting with a non-alpha character (handle `.blah` and `_blah`)
* Ignore all files not ending in `.ps1`

**Comment by 5ynax** [comment]
Is there a specific scenario that you are thinking of with this particular idea?

**Comment by 5ynax** [comment]
@valrkey meant to add you to the previous comment.

**Comment by valrkey** [comment]
@5ynax 
The specific use case I was thinking of is when Plugins are developed and downloaded through Git. Git repositories all have a folder `.git` in the root, so I didn't want the menu showing this `.git` folder as something to be navigated into.

The secondary use case for this would be to allow Plugins to have specific configuration files (`Config.psd1` or `.config` or whatever we want the naming scheme to be) to aid things like `Show Parameters` and provide plugin-specific default values.

**Comment by 5ynax** [comment]
@valrkey  Sounds good to me, just wanted to confirm there was nothing crazy that I wasn't considering. Thanks for clarifying.
