### ISSUE TITLE
Banner Text

### ISSUE THREAD

**Issue by 5ynax** [Asymmetric-InfoSec/Power-Response#20]
@5k33tz @valrkey - its time to pick our banner text! 

Pick your top three and lets see which one we like best!

**Comment by 5ynax** [comment]
1. http://patorjk.com/software/taag/#p=display&f=Graffiti&t=Power-Response
2. http://patorjk.com/software/taag/#p=display&f=Slant&t=Power-Response
3. http://patorjk.com/software/taag/#p=display&f=Crawford2&t=Power-Response

**Comment by valrkey** [comment]
1. [Slant](http://patorjk.com/software/taag/#p=display&f=Slant&t=Power-Response)
2. [Larry 3D](http://patorjk.com/software/taag/#p=display&f=Larry%203D&t=Power-Response)
3. [Graffiti](http://patorjk.com/software/taag/#p=display&f=Graffiti&t=Power-Response)
4. [Ivrit](http://patorjk.com/software/taag/#p=display&f=Ivrit&t=Power-Response)

![powres](https://user-images.githubusercontent.com/10157559/46486268-fef74180-c7c2-11e8-804d-2e330090cbf7.PNG)

**Comment by 5ynax** [comment]
@5k33tz @valrkey  - im liking slant so far! lets see if @5k33tz finds something magical...

**Comment by 5k33tz** [comment]
@5ynax @valrkey I'm diggin' the Slant or Ivrit.

**Comment by 5ynax** [comment]
@valrkey @5ynax - My final vote if for slant. What say ye?

**Comment by 5ynax** [comment]
haha added myself. meant @5k33tz

**Comment by valrkey** [comment]
Aye!
