### ISSUE TITLE
automatic analysis for plugins

### ISSUE THREAD

**Issue by 5ynax** [Asymmetric-InfoSec/Power-Response#203]
Plugins have a default naming convention of collect-<plugin name>. Have the framework look for an analysis script with the name Analyze-<plugin name> and prompt for running of the corresponding analysis plugins for each collect plugin

Example:
Collect-Prefetch.ps1 
Analyze-Prefetch.ps1

Prompt Example:

yadda yadda.. the plugin has finished
Would you like to run the corresponding analysis scripts for this plugin [n]: <require Y or N>
If yes... do the thing
If no... do not do the thing

**Comment by valrkey** [comment]
Closed with #242
