### ISSUE TITLE
Add an exit Power-Response option

### ISSUE THREAD

**Issue by 5ynax** [Asymmetric-InfoSec/Power-Response#22]
@valrkey @5k33tz - we could have an exit or quit power-response option on all the menus and sub-menus. what do you think about that?

**Comment by 5ynax** [comment]
@5k33tz, thats probably true. Maybe we should have one just in case... :)

**Comment by valrkey** [comment]
@5ynax Should we add that as a displayed menu item? Or should we interpret the text `exit` anywhere to exit the session?

**Comment by valrkey** [comment]
@5ynax did the `exit` keyword interpretation on the directory menu meet this requirement?

**Comment by 5ynax** [comment]
@valrkey yep. lets close this.
