### ISSUE TITLE
Default Parameters

### ISSUE THREAD

**Issue by valrkey** [Asymmetric-InfoSec/Power-Response#25]
Will we have any default parameters for people to set before dropping into a particular script file they wish to execute?

Possibilities:
* ComputerName
* IPAddress
...

**Comment by 5ynax** [comment]
@valrkey - I could see that being very helpful overall. Maybe we could add a condition where it looks for "global variables" and then if true use those, if not, make sure the user has specified parameters? We could add in a section above the menu where it shows the current values of those variables. 

Does that make things too complicated?

**Comment by valrkey** [comment]
@5ynax Yeah I can picture that and I don't think it will be too bad to implement. We could carry the `show` command into the directory menu and display all settable parameters there

**Comment by valrkey** [comment]
@5ynax Do we want to leave that totally per module? Or have global items too like `LogPath` and `OutputPath` be settable live in the session?

**Comment by 5ynax** [comment]
Design decision: not auto populate default parameter values, parameter carry over addresses this as needed.
