### ISSUE TITLE
Invoke-PRPlugin Function

### ISSUE THREAD

**Issue by valrkey** [Asymmetric-InfoSec/Power-Response#270]
Create `Invoke-PRPlugin` function to collect parameters and execute Power-Response plugins by `Name` or `Path`
* Will allow locally executing plugins to invoke other plugins
* Will take logic load off of `Invoke-RunCommand`

**Comment by valrkey** [comment]
@5ynax @5k33tz 

Should this function perform the `AutoAnalyze` function as well? In the scenario of a plugin (call it `Collect-WindowsArtifacts`) invokes a different plugin (call it `Collect-Prefetch`) with `AutoAnalyze` enabled, should the analysis plugin `Analyze-Prefetch` automatically be kicked off as well?

Conversely, we could keep the `AutoAnalyze` feature to only execute on the plugin the user intended to run which would only run a plugin named `Analyze-WindowsArtifacts` in the above example.

**Comment by 5ynax** [comment]
@valrkey 

To stay true to the intended functionality it would be best to have it determine what plugin was run and then figure out the corresponding analyze plugin is and run that according to how the framework would run by default.

Is that what you were thinking? 

5ynax

**Comment by valrkey** [comment]
Sure - so in both cases a plugin is executed, but one of them is executed
by the framework and the other is executed by another plugin. If I'm
tracking what you're saying then we should only autoanalyze plugins
executed from the framework?

**Comment by valrkey** [comment]
@5ynax 

Yep, we definitely want to keep the autoanalyze feature around, I guess my question was for whether we want to analyze all plugins that are executed, or just plugins that are executed from the framework itself.

The logic is all there, just depends on where we put it (`Invoke-RunCommand` vs `Invoke-PRPlugin`). I guess I would lean towards autoanalyzing any plugin that is executed regardless of how it was executed, but could be convinced otherwise.

**Comment by 5ynax** [comment]
@valrkey. 

I think we are on the same page. I think all plugins should be analyzed regardless of whether they are from a plugin directly or from a plugin that is being called from invoke-prplugin. 

Is that what you were saying?
