### ISSUE TITLE
Modify Import-Computers

### ISSUE THREAD

**Issue by valrkey** [Asymmetric-InfoSec/Power-Response#374]
**Describe the solution you'd like**
It would be nice to have a more general way to load data into parameters in Power-Response. Rather than restricting the Import to `ComputerName` alone, we should convert `Import-Computers` to a general `Import-Data` plugin. This plugin could have parameters `Session` (to make it locally executing), `Path` (CSV location), `Property` (which column to load), `ParameterName` (name of parameter to set).

**Comment by 5ynax** [comment]
complete
