### ISSUE TITLE
Implement Refresh

### ISSUE THREAD

**Issue by valrkey** [Asymmetric-InfoSec/Power-Response#5]
### New Files:
- Plugins\Refresh.ps1

### Details:
Add functionality to reload the Power-Response framework

**Comment by valrkey** [comment]
This might not be necessary if we are parsing the Plugins directory structure in real time?

**Comment by valrkey** [comment]
@5ynax @Mattski357

**Comment by 5ynax** [comment]
@valrkey: If every time we move to a new option (directory) it parses the contents real time, it wouldn't be necessary. The only question I would have then would be: would there be issues with the framework handling some unknown condition? I can't think of a scenario right off hand, but just making sure we are thinking outside the box.

**Comment by valrkey** [comment]
@5ynax: I think I've already handled the situation where someone adds a folder into the current menu directory, and I can't think of any other oddball scenario. Maybe we start developing dynamically until we have a solid case where that isn't a good idea?

**Comment by valrkey** [comment]
Sweet, I'll close this issue out then
