### ISSUE TITLE
Implement "Show Parameters" option(s)

### ISSUE THREAD

**Issue by 5ynax** [Asymmetric-InfoSec/Power-Response#7]
@valrkey @5k33tz : Should we consider adding menu options for 1) showing the current config options that are loaded into Power-Response? and 2) show the config options for a particular plugin that is loaded and ready to be used?

Users may want to know what their default values or specified values are while running power-response and/or if they need to troubleshoot why something is not performing as expected.

**Comment by valrkey** [comment]
@5ynax : sounds like a good plan to me - in practice do you see that appearing as an additional menu item on each page? Or would we want to implement a `help` function that showed additional functionality such as `Show Options` to keep the menu clean?

**Comment by 5ynax** [comment]
@valrkey I think I like the Show Parameters method to keep the menu clean. If we had a way to specify the plugin, and then show parameters, then specify parameters if necessary, then run it, i think that would be the best case scenario.

what do you think?

**Comment by valrkey** [comment]
@5ynax I agree, for the short term, I'm planning on developing a Show Options command for when a user has selected a file and is ready to send inputs it's way. After we get that up and running, we can think about extending that functionality to store session data for re-use across scripts run.

**Comment by 5ynax** [comment]
@valrkey - that might be the better answer anyway, i guess we will have to see if it is a pain to enter it in all the time. no sense in developing functionality that isnt needed.
