### ISSUE TITLE
Out-PRFile CSV Handling String Output

### ISSUE THREAD

**Issue by valrkey** [Asymmetric-InfoSec/Power-Response#75]
Plugins that return string output are returned as
```
length,
"#"
```

**Comment by 5ynax** [comment]
This is occurring more often. The Get-ASEP.ps1 plugin is difficult to implement with this condition present.

**Comment by 5ynax** [comment]
Update Out-PRFile to include a conversion of strings to a PS_Object so that string output can be added to a CSV output without the issue above.

**Comment by 5ynax** [comment]
Design decision: for string output, create a PSCustomObject and Power-Response will handle that gracefully.
